### ISSUE TITLE
Doesn't work with psx2psp custom games

### ISSUE THREAD

**Issue by ONElua** [LiEnby/NoPspEmuDrm#1]

**Comment by KuromeSan** [comment]
well yes? Because psx2psp do not create signed ps1 eboots and require popsloader.prx to work and that is obviously not included  in the offical pspemu firmware ..

**Comment by KuromeSan** [comment]
i think i should probablt check for a PGD in the psisoimg header though so atleast you dont get broken bubbles coming up from them .. (but thst would be a vitashell issue- and thats kind of already a bit messy code) psp seems to have lots of edge cases..

**Comment by ONElua** [comment]
Sceboot checks the integrity of the eboot.pbp

**Comment by LiEnby** [comment]
its not even like just patching a signature check. Iirc they dont have encrypted PGD iso header or compresses ISO data. i remember from chovy-sign because i looked at it to try inderstand the pops format & i know the actual pops format.

technically i could write my own psx2psp that works properly with it (& work on ofw psp) sort of like a pops sign_np .. 

Like chovysign can basically already do that its just annoying as it outputs a psvita cma backup and not just eboot.pbp 

but yeah like id be looking at writing a whole CFW for the pspemu just to support it .. which could be useful except like that also already exists.
