### ISSUE TITLE
Bad compatibility with some PSVita games?

### ISSUE THREAD

**Issue by LittleFIve233** [LiEnby/NoPspEmuDrm#6]
I installed this plugin, Minecraft (PCSG00302) appear the error code (C1-11843-7) . When i uninstalled it, the game will return to normal with no more errors, is this a bug?

**Comment by LiEnby** [comment]
![20230709_103149](https://github.com/LiEnby/NoPspEmuDrm/assets/39113159/f3ebb03f-eeec-4c75-be2c-44eed5656fac)
It seems to work fine? Though this is a different region version im downloading the pcsg one now .. I do wish i could specify *NPXS10028 instead of having to use *ALL however but it doesnt seem to work. My user module should unload itself on snything that isnt pspemu or shell though ?

**Comment by LiEnby** [comment]
Ok yes i seem to have issues installing the minecraft game ..

**Comment by LiEnby** [comment]
I stared at my code for ages wondering in what world the ecdsa signature for minecraft could be all 0xff then i had a thought- i patched ecdsa verify for rifs.. What if the offical rif code is actuslly trying to parse minecrafts rif file and is returning a success code ??

**Comment by LiEnby** [comment]
Alright that seems to fix it, i figured out the reason is because minecraft is "npdrm_free" so basically you can still start the game even without the correct license file but it will try start it as the demo, by patching ECDSA signature checks the offical rif handling code was trying to use the nonpdrm rif, and nonpdrm was not handling it,. i changed the ecdsa patch to only patch it out if the signature is not all 0xFF ..

**Comment by LittleFIve233** [comment]
> 

Nice work!
